version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgresql
    restart: unless-stopped
    networks: 
      connet:
        ipv4_address: 192.168.22.14
    env_file: ./postgres_env
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4:6.8
    container_name: pg-admin
    restart: unless-stopped
    networks: 
      connet:
        ipv4_address: 192.168.22.15
    env_file: ./pgadmin_env
    ports:
      - "8080:80"
    volumes:
      - "./pgadmin-data:/var/lib/pgadmin"

  

networks:
  connet:
    external: true